# Generated by Django 2.0.7 on 2018-07-27 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id_motivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id_solicitacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justicativa', models.TextField()),
                ('data_falta_inicio', models.DateField()),
                ('data_falta_fim', models.DateField()),
                ('data_reposicao', models.DateField()),
                ('data_aula', models.DateField()),
                ('outro', models.CharField(blank=True, max_length=200, null=True, verbose_name='outro')),
                ('descricao', models.TextField()),
                ('Componente', models.CharField(max_length=100, verbose_name='Componente')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='matricula')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Turma'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Usuario'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Motivo'),
        ),
    ]
